### PR TITLE
Add HRRR interface

### PR DESCRIPTION
**Pull request by ewquon**
This builds on top of Alicia's code and supercedes the `NREL/SSRS:alicia-dev` branch (https://github.com/NREL/SSRS/tree/alicia-dev).

### CODE REVIEW

**Comment by ewquon** [comment]
@rthedin Did you help Alicia with the wind calculation in https://github.com/NREL/SSRS/pull/13/commits/2db9e2cea0b49689a64a41d3a9dee4c781618c55 and is there any "gotcha" with switching back to the standard calculation?

**Comment by rthedin** [comment]
No, that was not me. I haven't touched the wind calculation at all.

**Comment by rthedin** [comment]
What I've done was related to the longitude degrees E vs W. I know we talked about this so I will leave it here in case we need to refer back to it at some point. In earlier code, I wrote this function
https://github.com/NREL/SSRS/blob/8fc10b8f2865548e1229bf5070e8031b1b42b7da/ssrs/hrrr/hrrr.py#L456
Inside of which, I had the transformation of conventions:
https://github.com/NREL/SSRS/blob/8fc10b8f2865548e1229bf5070e8031b1b42b7da/ssrs/hrrr/hrrr.py#L434-L435

I haven't taken a close look at the current code to see if Alicia rewrote and/or got rid of that. It worked well for my purposes and I would get a single variable at a time to calculate whatever I needed to calculate.

**Comment by ewquon** [comment]
FYI @rthedin and @rimplesandhu... I've made a number of changes, detailed in the commits above. A short summary:
* I've changed the behavior of `get_xarray_for_regex` function to save and return a dataset that follows the **degrees E/W** convention with +/- values, respectively; stated differently, the range of longitudes is now [-180, 180]
* The default projection is Albers Equal Area Conic, but I've added an option to retrieve and interpolate the wind map based on the "native" coordinate reference system (CRS). This should be Lambert Conformal Conic for HRRR, but I coded it up so that it will in general scrape the appropriate projection string directly from the GRIB2 file. 
* If you call `wind_velocity_direction_at_altitude(..., projection=native)`, this will return data on a truly Cartesian grid and values interpolated with true bilinear interpolation.
* What was described as bilinear interpolation before was actually B-spline interpolation, which can produce bogus results; this has been replaced with the more general scattered-data interpolator, `griddata`.

Plots of u and v fields are shown below. I'm not concerned about the small differences in the retrieved data--there are no guarantees that we are pulling from exactly  the same archived data. 

**Original, manually downloaded field**
nearest u,v = 12.92, 4.758 m/s
uv--manual_download

**Field downloaded from Herbie**
nearest u,v = 12.36, 4.677 m/s
uv--herbie

**Transformed points with `ssrs.HRRR.wind_velocity_direction_at_altitude` (Albers projection)**
original `interp2d` u,v = 11.31, -16.09 m/s <-- **!!!**
updated `griddata` u,v = 11.47, 4.147 m/s
uv--herbie_scatplotxy

**Transformed field with `ssrs.HRRR.wind_velocity_direction_at_altitude` (native Lambert projection)**
bilinear interpolation on Cartesian mesh: u,v = 11.55, 4.197
uv--herbie_colormesh_lcc

**Comment by ewquon** [comment]
If you guys are doing lots of interpolations on a single grid, it might make sense to use the native CRS transform. I put in a new function `get_var_on_native_grid` that will almost instantly give you all fields on a regular grid in xarray.Dataset form. From there, bilinear interpolation is extremely efficient.

**Pull request merged**
